export const SEAT = "seat"
export const ORDERS_LIMIT = "ordersLimit"
export const ORDERS = "orders"
export const CARRIAGE = "carriage"
export const CARRIAGES = "carriages"
export const ROUTE_CARRIAGE = "routeCarriage"
export const COMPANY_ROUTES_CARRIAGES = "companyRoutesCarriages"
export const AVAILABLE_SEATS = "availableSeats"
export const ROUTE_BY_DATE = "routeByDate"
export const STOP_BY_DATE = "stopByDate"
export const SOURCE_BY_DATE = "sourceByDate"
export const BOOKINGS_LIMIT = "bookingsLimit"
export const CREATED_BY_ID = "createdById"
export const ARRIVAL_STOP_ID = "arrivalStopId"
export const DEPARTURE_STOP_ID = "departureStopId"

export const CREATED_ORDER = "CREATED_ORDER"
export const UPDATED_ORDER = "UPDATED_ORDER"
export const DELETED_ORDER = "DELETED_ORDER"

export const UPDATED_ROUTE_CARRIAGES = "UPDATED_ROUTE_CARRIAGES"

export const UPDATED_AVAILABLE_SEATS = "UPDATED_AVAILABLE_SEATS"
export const UPDATED_ROUTE_BY_DATE = "UPDATED_ROUTE_BY_DATE"
export const UPDATED_STOP_BY_DATE = "UPDATED_STOP_BY_DATE"
export const UPDATED_SOURCE_BY_DATE = "UPDATED_SOURCE_BY_DATE"
